version: 1.0

steps:
  - name: Install Python Dependencies
    script:
      - python3 -m pip install --upgrade pip
      - pip install pyTelegramBotAPI  # telebot is part of this package

  - name: Make Binary Executable
    script:
      - chmod +x venompapa  # Ensure venompapa is in the working directory or provide the path

  - name: Run Python Script
    script:
      - python3 ven.py  # Ensure ven.py is in the working directory or provide the path
